name: first-workflow-action

on: [push]

jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo statement
        run: echo "Hello Midde" 
      - name: second multiple statements 
        run: |
          echo "Hello Midde file " > myfile.txt
          cat myfile.txt
          rm -rf myfile.txt